#!/usr/bin/env python3
"""Report which external/generated data files the pipeline needs are present.

Run as `pali-check-data` (after `pip install`) or `python src/pali_check_data.py`.
Exits non-zero if any REQUIRED resource is missing, so it can gate CI / setup.
"""
import sys
from pathlib import Path

DATA_DIR = Path(__file__).resolve().parent.parent / "data"

# (relative path, required?, what it is / how to get it)
RESOURCES = [
    ("dpd/dpd.db", True,
     "Digital Pāli Dictionary SQLite DB (lemmatization + collation validation)"),
    ("dpd/sandhi_rules.tsv", True,
     "DPD sandhi rules for the enhanced lemmatizer"),
    ("dppn/proper_names.json", False,
     "Dictionary of Pāli Proper Names (proper-noun lemmas)"),
    ("canonical", True, "Parsed canonical source text (input to lemmatization)"),
    ("lemmatized", False, "Lemmatized corpus (generated by lemmatize_canon.py)"),
]


def _describe(path: Path) -> str:
    if path.is_dir():
        n = sum(1 for _ in path.rglob("*.json"))
        return f"dir, {n} json files"
    size = path.stat().st_size
    for unit in ("B", "KB", "MB", "GB"):
        if size < 1024 or unit == "GB":
            return f"{size:.0f}{unit}" if unit == "B" else f"{size:.1f}{unit}"
        size /= 1024
    return ""


def main() -> int:
    print(f"Checking data under {DATA_DIR}\n")
    missing_required = []
    for rel, required, desc in RESOURCES:
        path = DATA_DIR / rel
        present = path.exists() and (not path.is_dir() or any(path.iterdir()))
        tag = "REQUIRED" if required else "optional"
        if present:
            print(f"  [OK]      {rel:28} ({_describe(path)}) — {desc}")
        else:
            print(f"  [MISSING] {rel:28} [{tag}] — {desc}")
            if required:
                missing_required.append(rel)

    print()
    if missing_required:
        print(f"FAIL: {len(missing_required)} required resource(s) missing: "
              f"{', '.join(missing_required)}")
        return 1
    print("OK: all required data present.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
